#	$FabBSD$
#	$OpenBSD: Makefile,v 1.31 2008/05/15 20:19:11 kettenis Exp $
#	$NetBSD: Makefile,v 1.5 1995/09/15 21:05:21 pk Exp $

SUBDIR=	dev/microcode \
	arch/alpha arch/amd64 arch/armish \
	arch/i386 \
	arch/macppc \
	arch/sparc arch/sparc64

.include <bsd.subdir.mk>
