.\"	$FabBSD$
.\"
.\" Copyright (c) 2009-2010 Hypertriton, Inc. <http://hypertriton.com/>
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT,
.\" INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
.\" (INCLUDING BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
.\" SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
.\" STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
.\" IN ANY WAY OUT OF THE USE OF THIS SOFTWARE EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd $Mdocdate: January 5 2010 $
.Dt UNITS 7
.Os
.Sh NAME
.Nm units
.Nd standard FabBSD units
.Sh DESCRIPTION
Standard FabBSD coordinates (see
.Xr coordinates 7 ) ,
as well as the
.Dv UNITS
environment variable may take on the following values:
.Sh SI UNITS
.Bl -tag -compact -width "mm "
.It m
Metres
.It km
Kilometres (10^3 m)
.It cm
Centimetres (10^-2 m)
.It mm
Millimetres (10^-3 m)
.It um
Microns (10^-6 m)
.It nm
Nanometres (10^-9 m)
.It pm
Picometres (10^-12 m)
.El
.Sh US CUSTOMARY UNITS
.Bl -tag -compact -width "in "
.It in
Inches
.It ft
Feet
.It yd
Yards
.El
.Sh UNITS OF ANGLE
.Bl -tag -compact -width "rad "
.It rad
Radians
.It deg
Degrees
.It rev
Revolutions
.El
.Sh SEE ALSO
.Xr coordinates 7 ,
.Xr environ 7 ,
.Xr units 1
.Sh HISTORY
The
.Nm
manual page first appeared in FabBSD 1.0.
