.\"
.\" Copyright (c) 2009 Hypertriton, Inc. <http://hypertriton.com/>
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT,
.\" INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
.\" (INCLUDING BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
.\" SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
.\" STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
.\" IN ANY WAY OUT OF THE USE OF THIS SOFTWARE EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd $Mdocdate: April 3 2009 $
.Dt CNCJOGSTEP 2
.Os
.Sh NAME
.Nm cncjogstep
.Nd manual motion of motorized axis (stepwise)
.Sh SYNOPSIS
.Fd #include <sys/cnc.h>
.Ft int
.Fn cncjogstep "void"
.Sh DESCRIPTION
.Nm
moves motorized axes (e.g.,
.Xr servo 4
devices) in response to signals generated by the registered
.Xr mpg 4
(manual pulse generator) devices.
.Pp
Unlike
.Xr cncjog 2 ,
.Nm
translates input steps directly to servo steps, without applying limits
on velocity or acceleration.
When optical encoders are used as
.Xr mpg 4
devices,
.Nm
is useful in manipulator-like devices.
.Pp
The
.Nm
call will block until an
.Xr estop 4
event is raised.
.Sh RETURN VALUES
If the motion is successful, a 0 value is returned.
A return value of \-1 indicates an error, which is further specified in the global
.Va errno .
.Sh ERRORS
The
.Fn cncmove
will fail if:
.Bl -tag -width Er
.It Bq Er ENXIO
The trajectory planner has not been calibrated (see
.Xr cncctl 8 ) .
.El
.Sh SEE ALSO
.Xr cnc 3 ,
.Xr cncjog 2 ,
.Xr cncmove 2
.Sh HISTORY
The
.Nm
function appeared in FabBSD 1.0.
