.\"
.\" Copyright (c) 2011 Hypertriton, Inc. <http://hypertriton.com/>
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT,
.\" INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
.\" (INCLUDING BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
.\" SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
.\" STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
.\" IN ANY WAY OUT OF THE USE OF THIS SOFTWARE EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd $Mdocdate: September 27 2011 $
.Dt CNCSPOTWELDSELECT 2
.Os
.Sh NAME
.Nm cncspotweldselect
.Nd return spot welder select status
.Sh SYNOPSIS
.Fd #include <sys/cnc.h>
.Ft int
.Fn cncspotweldselect "int spotwelder"
.Sh DESCRIPTION
.Nm
returns 1 if the select switch for the specified spot welding unit
is in the ON state.
.Sh RETURN VALUES
If the select switch is ON, a value of 1 is returned, otherwise 0 is returned.
A return value of \-1 indicates an error, which is further specified in the
global
.Va errno .
.Sh ERRORS
The
.Fn cncposweldselect
call will fail if:
.Bl -tag -width Er
.It Bq Er ENODEV
The specified spot welder unit does not exist.
.El
.Sh SEE ALSO
.Xr cncspotweld 2 ,
.Xr cncspotweldtrig 2 ,
.Xr cnc 3
.Sh HISTORY
The
.Nm
function appeared in FabBSD 1.0.
