#	$FabBSD$
#	$OpenBSD: Makefile,v 1.53 2007/10/18 19:21:36 espie Exp $
#	$NetBSD: Makefile,v 1.20.4.1 1996/06/14 17:22:38 cgd Exp $

SUBDIR=	csu libarch libc libcnc libcurses \
	libdes libedit libevent libexpat \
	libform libkvm libl libm libmenu \
	libocurses libpanel libpthread librpcsvc \
	libskey libssl libusbhid libutil libwrap liby libz

.include <bsd.own.mk>

.include <bsd.subdir.mk>
