#	$FabBSD
#	$OpenBSD: Makefile,v 1.142 2008/06/15 04:44:30 sturm Exp $

.include <bsd.own.mk>

SUBDIR=	adduser amd apm apmd arp \
	chroot cncctl config cron dev_mkdb fdformat \
	gpioctl hotplugd ifstated inetd iostat \
	kgmon kvm_mkdb lpr memconfig \
	mtree openssl \
	pcidump pkg_add portmap procmap pstat pwd_mkdb \
	rdate rdconfig rmt rpc.lockd rpc.statd rtsold sensorsd sliplogin \
	slstats snmpctl snmpd syslogc syslogd sysmerge \
	tcpdrop traceroute traceroute6 \
	usbdevs user vipw watchdogd wsconscfg wsfontload \
	zdump zic

.include <bsd.subdir.mk>

