#	$FabBSD$
#	$OpenBSD: Makefile,v 1.45 2007/03/23 02:17:52 ray Exp $
#	$NetBSD: Makefile,v 1.35 1996/04/03 21:20:52 chuck Exp $

.include <bsd.own.mk>

SUBDIR+=	gcc cxxfilt groff lynx binutils

# Do these last; texinfo builds the info 'dir' file, perl must be after binutils
SUBDIR+=	perl texinfo

.include <bsd.subdir.mk>
