#	$FabBSD$
#	$OpenBSD: Makefile,v 1.44 2007/05/18 16:08:12 deraadt Exp $
#	from: @(#)Makefile	5.7 (Berkeley) 4/1/91

.include <bsd.own.mk>

SUBDIR=	ftpd getNAME getty makewhatis tcpd tftpd
SUBDIR+=login_passwd login_skey login_reject login_chpass login_lchpass
SUBDIR+=ld.so

.include <bsd.subdir.mk>
