.\"	$FabBSD$
.\"	Public domain
.\"
.Dd $Mdocdate: April 1 2009 $
.Dt MOVE 1
.Os
.Sh NAME
.Nm move
.Nd move machine axes
.Sh SYNOPSIS
.Nm move
.Op Fl iv
.Op Fl S Ar startvel
.Op Fl F Ar feedrate
.Op Fl A Ar accellim
.Op Fl J Ar jerklim
.Op Ar pos ...
.Sh DESCRIPTION
The
.Nm
command is the simplest interface to FabBSD's trajectory planner.
.Nm
executes coordinated motion of the machine axes (e.g.,
.Xr servo 4
devices) from the current position (see
.Xr cncctl 8 )
to
.Ar pos .
If multiple position arguments are specified, the machine will move to
each one successively.
.Nm
blocks and returns once the motions are complete (or an emergency stop
raised).
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl v
Enable verbose output.
.It Fl i
Interpret the input position(s) as incremental instead of absolute.
.It Fl s
Specify an initial, starting velocity in steps/s.
Default is 0.
.It Fl f
Specify an optimal feed rate in steps/s.
The trajectory planner may or may not achieve this feed rate (depending on the
other parameters and travel distance).
Default is machine-dependent.
.It Fl a
Specify the limit on acceleration in steps/s^2.
Default is machine-dependent.
.It Fl j
Specify the limit on jerk in steps/s^3.
Default is machine-dependent.
.El
.Sh ENVIRONMENT
.Bl -tag -width UNITS
.It Ev UNITS
Set to
.Sq metric
or
.Sq inch .
Defaults to
.Sq metric .
.El
.Sh SEE ALSO
.Xr coordinates 7 ,
.Xr servo 4 ,
.Xr tools 8
.Sh HISTORY
The
.Nm
command first appeared in FabBSD 1.0.
