#	$FabBSD$
#	$OpenBSD: Makefile,v 1.88 2008/06/09 22:23:18 mbalmer Exp $

SUBDIR=	atactl badsect ccdconfig dhclient \
	disklabel dmesg dumpfs fdisk fsck fsck_ext2fs fsck_ffs  \
	fsck_msdos fsirand growfs ifconfig init iopctl \
	kbd ldattach mknod modload modunload mount \
	mount_cd9660 mount_ext2fs mount_ffs mount_msdos \
	mount_nfs mount_udf \
	mount_vnd mountd ncheck_ffs newfs newfs_msdos \
	nfsd nologin ping ping6 \
	reboot route rtsol savecore scan_ffs \
	scsi shutdown slattach swapctl sysctl ttyflags tunefs \
	umount wpa-psk wsconsctl

.include <bsd.subdir.mk>
