#	$FabBSD$
#	$OpenBSD: Makefile,v 1.109 2008/06/04 21:12:49 deraadt Exp $

.include <bsd.own.mk>

SUBDIR= apply apropos arch asa asn1_compile awk banner basename bc \
	cap_mkdb cdio chpass cmp col colcrt colrm \
	column comm compile_et compress cpp crontab csplit ctags cut \
	dc deroff diff diff3 dirname drillsize du encrypt env expand false \
	file file2c find fmt fold fstat ftp gencat gerbdrill getcap \
	getconf getent getopt grep gzsig head hexdump id \
	indent infocmp ipcrm ipcs jog \
	join jot kdump ktrace lam last lastcomm less lex lndir \
	lock logger login logname look lorder m4 make man mesg mg \
	mkdep mklocale mktemp msgs modstat \
	motioncap move nc netstat newsyslog \
	nfsstat ngc nice nm nohup cvs pagesize passwd paste patch pctr \
	pkg-config pkill \
	pr printenv printf rcs \
	readlink renice rev rpcgen rpcinfo rs \
	sdiff script sed sendbug shar showmount skey \
	skeyaudit skeyinfo skeyinit sort split ssh stat su systat \
	sudo tail tcopy tee telnet tftp tic time tip \
	top touch tput tr true tset tsort tty usbhidaction usbhidctl ul uname \
	unexpand unifdef uniq units \
	unvis users vgrind vi vis vmstat w wall wc \
	what whatis which who window write xargs xinstall \
	xstr yacc yes

.include <bsd.subdir.mk>
